### ISSUE TITLE
Standardized name on the Rapid Test certificate is not standard

### ISSUE THREAD

**Issue by alanrick** [corona-warn-app/cwa-quick-test-frontend#278]
## Describe the bug
When I receive the test-certificate from a rapid test using the CWA workflow the standardized name does not match the standardized name on my immunization certificate.

## Expected behaviour
I would expect the standardized name on the rapid test certificate and immunization certificate to be identical, so that they can be correlated for the 2G+ status.

## Steps to reproduce the issue

Name: _Alan Rick Johnson_
Standardized name on **Immunization** Certificate: _JOHNSON<<ALAN<RICK_
Standardized name on **Rapid Test** Certificate: _JOHNSON<<ALANRICK_

## Technical details

- CWA is iOS Latest. The name comes from the CWA Rapid Test profile and is not manipulated by the tester.

## Additional context

This might be important apps that validate covid certificates, for example in other countries or apps that validate against the Personal Ausweis.

**Comment by Ein-Tim** [comment]
The test centres are responsible to correctly enter the standardized name. 
See also https://github.com/corona-warn-app/cwa-documentation/issues/810

**Comment by alanrick** [comment]
Apologies for the duplicate, I'd not expected this to be in the documentation repository. 
I thought the test-center uses 100% the CWA Workflow software. I.e. The scanning app that the tester uses comes from the CWA project, and the name comes from my CWA client. I hadn't realized each test-center uses their own backend software to generate the certificates and I don't understand why this is necessary.

Nevertheless I'm closing the ticket.

**Comment by vaubaehn** [comment]
@alanrick 
Depends on the test center: some use the official portal from TSI, where the standardized names still need to be entered manually.
Other test centers use their own software, where problems with standardized names would need to be detected during the "Abnahmetest" when provider goes into production.
Today, I brought this subject again to attention to all stakeholders: https://github.com/corona-warn-app/cwa-quick-test-frontend/issues/185#issuecomment-1021142950

**Comment by alanrick** [comment]
At this testcenter which I used yesterday she was using a Web form where she does have to key in the standardized name and firstname. **Schnelltestportal.de**
Is that the TSI one? Has that been improved since I took the photo yesterday? I noticed corona-warn-app/cwa-documentation#810 has now been closed.

![CWAStandardName](https://user-images.githubusercontent.com/7034358/152142566-e1dba4a5-0255-4fc2-80e6-0519d00fecd9.png)

**Comment by vaubaehn** [comment]
Hi @alanrick ,
yes, schnelltestportal.de is the TSI's one. The request to improve the portal to automatically fill out the "standardized name fields" is open since summer 2021.
I'd recommend to follow issue https://github.com/corona-warn-app/cwa-quick-test-frontend/issues/185 on any updates about this. I also suggested to improve/harmonize the quality of standardized name transliteration for all test centers that do not use the Schnelltestportal but which are connected to TSI's backend: https://github.com/corona-warn-app/cwa-quick-test-frontend/issues/185#issuecomment-1021142950
Doesn't look like we'll see improvements in a timely manner, unfortunately.
Please feel free to comment your thoughts in the referenced issue.
Hope that helps,
v.
